version: '3'
services:
  orbitr-postgres:
    platform: linux/amd64
    image: postgres:12-bullseye
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=orbitr
    ports:
      - "5432:5432"
    volumes:
      - "orbitr-db-data:/var/lib/postgresql/data"

  orbitr:
    platform: linux/amd64
    depends_on:
      - orbitr-postgres
    build:
      # set build context to the root directory of the go monorepo
      context: ../../../
      args: 
         GRAVITY_VERSION: ${GRAVITY_VERSION:-}
      dockerfile: services/orbitr/docker/Dockerfile.dev
    restart: on-failure
    ports:
      - "8000:8000"
      - "11725:11725"
    environment:
      - DATABASE_URL=postgres://postgres@host.docker.internal:5432/orbitr?sslmode=disable
      - NETWORK=testnet
      - PER_HOUR_RATE_LIMIT=0
    command: ["--apply-migrations"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  orbitr-db-data:
